spring:
  mvc:
    view:
      prefix: resources/templates
      suffix: html
  datasource:
    url: jdbc:mysql://localhost:3306/webapp?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 12345678
    initialization-mode: always
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57InnoDBDialect
        storage_engine: innodb
server:
  error:
    whitelabel:
      enabled: false  
logging:
  level:
    org:
      springframework:
        security: DEBUG
    








